name: 'dataops_sales'
version: '1.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  dataops_sales:
    staging:
      materialized: view
    marts:
      materialized: table
